export const BKZ_SOURCE='https://assets.cdn.netze-bw.de/xytfb1vrn7of/3WkwLb2wCAE2YcQuG0YU4m/cff72cf6af73c9b225d0268390f45ebf/preisuebersicht-baukostenzuschuss-bkz-strom.pdf';
export const POSITIONS=[
 {key:'cable',label:'Kabel und Leitungen',unit:'€/m',quantity:'route'},
 {key:'civil',label:'Tiefbau',unit:'€/m',quantity:'route'},
 {key:'crossing',label:'Querungen',unit:'€/Querung',quantity:'crossing'},
 {key:'transformer',label:'Transformatoren',unit:'€/MW',quantity:'power'},
 {key:'switchgear',label:'Schaltanlagen',unit:'€ pauschal',quantity:'one'},
 {key:'protection',label:'Schutz- und Messtechnik',unit:'€ pauschal',quantity:'one'},
 {key:'planning',label:'Planung und Genehmigungen',unit:'€ pauschal',quantity:'one'},
 {key:'bkz',label:'Baukostenzuschuss',unit:'€/kW',quantity:'kw'},
 {key:'other',label:'Weitere Betreiberpositionen / Netzverstärkung',unit:'€ pauschal',quantity:'one'}
];
export function defaultModel(){return {factors:[1.15,1.35,1.7],prices:Object.fromEntries(POSITIONS.map(p=>[p.key,[null,null,null]])),level:'mv',crossings:null,source:'',priceDate:'',direction:'draw',project:'commercial'};}
export function voltages(o){return String(o.tags?.voltage||'').split(';').map(x=>/^\d+(\.\d+)?$/.test(x.trim())?Number(x):NaN).filter(Number.isFinite);}
export function voltageBand(v){return v>=220000?'ehv':v>=60000?'hv':v>=1000?'mv':v>0?'lv':'unknown';}
export function bands(o){const v=voltages(o);return v.length?[...new Set(v.map(voltageBand))]:['unknown'];}
export function distance(a,b){const rad=Math.PI/180;const dlat=(b.lat-a.lat)*rad,dlon=(b.lon-a.lon)*rad;const h=Math.sin(dlat/2)**2+Math.cos(a.lat*rad)*Math.cos(b.lat*rad)*Math.sin(dlon/2)**2;return 6371*2*Math.asin(Math.min(1,Math.sqrt(h)));}
export function targetLevel(req){return req.level==='auto'?(req.mw<=20?'mv':req.mw<=150?'hv':'ehv'):req.level;}
export function validateRequest(req){if(!Number.isFinite(req.mw)||req.mw<=0||req.mw>1000)throw Error('Bitte eine Leistung größer 0 und höchstens 1.000 MW eingeben.');if(!['draw','feed','both'].includes(req.direction)||!['commercial','industry','storage','charging','generation'].includes(req.project)||!['auto','mv','hv','ehv'].includes(req.level)||!['single','n1'].includes(req.redundancy))throw Error('Ungültiger Anschlussbedarf.');return req;}
export function matches(o,filters){return (!filters||((filters.voltage==='all'||bands(o).includes(filters.voltage))&&(filters.operator==='all'||(o.tags.operator||'Unbekannt')===filters.operator)&&(filters.type==='all'||filters.type===o.kind)));}
export function candidates(stations,site,req,filters){validateRequest(req);const level=targetLevel(req);return stations.filter(o=>matches(o,filters)&&bands(o).includes(level)&&!['traction','generation','industrial','minor_distribution'].includes(o.tags.substation)&&!/(^|;)(16[.,]7|0)(;|$)/.test(o.tags.frequency||'')&&!/^(yes|construction|disused)$/.test(o.tags.disused||o.tags.construction||'')).map(o=>({...o,km:distance(site,o),level})).filter(o=>o.km<=50).sort((a,b)=>a.km-b.km).filter((o,i,arr)=>arr.findIndex(x=>distance(o,x)<.15&&(o.tags.name&&o.tags.name===x.tags.name))===i||!o.tags.name).slice(0,3);}
export function validateModel(m){if(!Array.isArray(m.factors)||m.factors.length!==3||m.factors.some(x=>!Number.isFinite(x)||x<1||x>10)||!(m.factors[0]<=m.factors[1]&&m.factors[1]<=m.factors[2]))throw Error('Trassenfaktoren müssen zwischen 1 und 10 liegen und aufsteigend sein.');if(!['mv','hv','ehv'].includes(m.level))throw Error('Ungültige Preisebene.');if(m.crossings!==null&&(!Number.isInteger(m.crossings)||m.crossings<0||m.crossings>10000))throw Error('Querungsanzahl muss eine ganze, nicht negative Zahl sein.');let hasPrice=false;for(const p of POSITIONS){const a=m.prices[p.key];if(!Array.isArray(a)||a.length!==3||a.some(x=>x!==null&&(!Number.isFinite(x)||x<0||x>1e12)))throw Error('Preise müssen leer oder endliche, nicht negative Zahlen sein.');if(a.every(x=>x!==null)&&!(a[0]<=a[1]&&a[1]<=a[2]))throw Error(`${p.label}: Niedrig ≤ Mittel ≤ Hoch erforderlich.`);hasPrice ||=a.some(x=>x!==null);}if(hasPrice&&(!m.source.trim()||!/^\d{4}-\d{2}-\d{2}$/.test(m.priceDate)))throw Error('Bitte Quelle / eigene Annahmen und Preisstand für Ihre Preise angeben.');return m;}
export function estimate(candidate,req,model){validateRequest(req);validateModel(model);const route=model.factors.map(f=>candidate.km*1000*f);const rows=POSITIONS.map(p=>{let rates=model.level===candidate.level&&model.direction===req.direction&&model.project===req.project?[...model.prices[p.key]]:[null,null,null];let source='Unbekannt – Angebot oder eigene Annahme erforderlich',date=null,status='unknown';if(rates.some(x=>x!==null)){source=model.source;date=model.priceDate;status='assumed';}if(p.key==='bkz'&&rates.every(x=>x===null)&&/^Netze BW(?: GmbH)?$/.test(candidate.tags.operator||'')&&req.direction!=='feed'&&candidate.level==='hv') {rates=[162.97,162.97,162.97];source=BKZ_SOURCE;date='2026-01-01';status='published-conditional';}let qty=p.quantity==='route'?route:p.quantity==='power'?[req.mw,req.mw,req.mw]:p.quantity==='kw'?[req.mw*1000,req.mw*1000,req.mw*1000]:p.quantity==='crossing'?[model.crossings,model.crossings,model.crossings]:[1,1,1];return {...p,rates,qty,values:rates.map((r,i)=>r===null||qty[i]===null?null:r*qty[i]),source,date,status};});const missing=rows.filter(p=>p.values.some(x=>x===null)).map(p=>p.label);const blockers=[];if(req.redundancy==='n1')blockers.push('N−1: unabhängiger zweiter Netzpfad und Zusatzkosten nicht ermittelt.');if(req.project==='storage'&&req.direction!=='both')blockers.push('Speicher: Bezug und Einspeisung sowie Ladeleistung getrennt beim Betreiber klären.');const subtotal=[0,1,2].map(i=>rows.reduce((s,r)=>s+(r.values[i]??0),0));return {route,rows,missing,blockers,subtotal,total:missing.length||blockers.length?null:subtotal,knownCount:rows.filter(r=>r.values.every(v=>v!==null)).length,disclaimer:'Unverbindliche Vorabschätzung. Keine Kapazitäts- oder Anschlusszusage. Alle Summen netto, ohne laufende Betriebskosten.'};}
export function pointInRing(point,ring){let inside=false;const x=point.lon,y=point.lat;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const [xi,yi]=ring[i],[xj,yj]=ring[j];if(((yi>y)!==(yj>y))&&(x<(xj-xi)*(y-yi)/(yj-yi)+xi))inside=!inside;}return inside;}
export function inGermany(p,boundary){if(!Number.isFinite(p.lat)||!Number.isFinite(p.lon))return false;return boundary.coordinates.some(poly=>pointInRing(p,poly[0])&&!poly.slice(1).some(r=>pointInRing(p,r)));}
export function validPolygon(points){if(points.length<3)return false;const cross=(a,b,c)=>(b.lon-a.lon)*(c.lat-a.lat)-(b.lat-a.lat)*(c.lon-a.lon);let area=0;for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length];area+=a.lon*b.lat-b.lon*a.lat;if(distance(a,b)<.001)return false;for(let j=i+2;j<points.length;j++){if((j+1)%points.length===i)continue;const c=points[j],d=points[(j+1)%points.length];if(cross(a,b,c)*cross(a,b,d)<=0&&cross(c,d,a)*cross(c,d,b)<=0)return false;}}return Math.abs(area)>1e-9;}
export function representativePoint(points){const mean={lat:points.reduce((s,p)=>s+p.lat,0)/points.length,lon:points.reduce((s,p)=>s+p.lon,0)/points.length};return pointInRing(mean,points.map(p=>[p.lon,p.lat]))?mean:points[0];}
