import {writeFileSync,mkdirSync} from 'node:fs';
import assert from 'node:assert/strict';
const tabs=await (await fetch(process.env.CDP_URL||'http://127.0.0.1:9334/json/list')).json();const tab=tabs.find(t=>t.type==='page');
const ws=new WebSocket(tab.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let id=0;const pending=new Map(),errors=[];
ws.addEventListener('message',ev=>{const m=JSON.parse(ev.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p?.reject(Error(JSON.stringify(m.error))):p?.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);});
function send(method,params={}){const cid=++id;return new Promise((resolve,reject)=>{pending.set(cid,{resolve,reject});ws.send(JSON.stringify({id:cid,method,params}));});}
async function evaluate(expression){const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const requests=[];ws.addEventListener('message',ev=>{const m=JSON.parse(ev.data);if(m.method==='Network.requestWillBeSent')requests.push(m.params.request.url);});
async function until(expression){for(let i=0;i<200;i++){if(await evaluate(expression))return;await wait(100);}throw Error('Timed out: '+expression);}
await send('Page.enable');await send('Runtime.enable');await send('Network.enable');await send('Network.setCacheDisabled',{cacheDisabled:true});
await send('Network.setBlockedURLs',{urls:['*tile.openstreetmap.org/*','*wms.nrw.de/*']});
await send('Page.addScriptToEvaluateOnNewDocument',{source:`window.testTools={};Object.defineProperty(document,'modelContext',{value:{registerTool(tool){window.testTools[tool.name]=tool;}}});window.longTasks=[];new PerformanceObserver(list=>window.longTasks.push(...list.getEntries().map(e=>e.duration))).observe({type:'longtask',buffered:true});`});
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});
await send('Page.navigate',{url:process.env.TEST_URL||'http://127.0.0.1:8788/'});
await until(`document.querySelector('#data-status')?.textContent.includes('16 Bundesländer')`);
assert.equal(await evaluate(`document.querySelector('#state-filter').options.length`),17);
mkdirSync('/tmp/anschluss-regions-results',{recursive:true});
const desktop=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});writeFileSync('/tmp/anschluss-regions-results/desktop.png',Buffer.from(desktop.data,'base64'));
assert.ok(!requests.some(url=>/data\/(stations|lines)\.json/.test(url)),'No national infrastructure downloads');
assert.ok(!requests.some(url=>url.includes('data/states/')),'Overview downloads no state chunks');
const initial=await evaluate(`performance.getEntriesByType('resource').filter(e=>e.name.includes('/data/')).map(e=>({url:e.name,bytes:e.decodedBodySize}))`);
await send('Input.dispatchMouseEvent',{type:'mousePressed',x:850,y:340,button:'left',clickCount:1});
await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:850,y:340,button:'left',clickCount:1});
await until(`document.querySelector('#state-filter').value!==''`);
assert.ok(await evaluate(`document.querySelector('#location-summary').textContent.includes('Klicken Sie')`),'State click navigates without selecting a project site');
await evaluate(`document.querySelector('#fit-germany').click()`);
await until(`document.querySelector('#data-status').textContent.includes('16 Bundesländer')`);
await evaluate(`document.querySelector('#state-filter').value='DE-BE';document.querySelector('#state-filter').dispatchEvent(new Event('change'));`);
await until(`document.querySelector('#data-status').textContent.includes('Objekte im Ausschnitt')`);
assert.ok(requests.some(url=>url.includes('DE-BE-stations')));
assert.ok(!requests.some(url=>url.includes('DE-BY-')),'Berlin must not load Bavaria');
const countBefore=requests.filter(url=>url.includes('data/states/')).length;
await evaluate(`document.querySelector('#retry-data').click()`);
await until(`document.querySelector('#data-status').textContent.includes('Objekte im Ausschnitt')`);
assert.equal(requests.filter(url=>url.includes('data/states/')).length,countBefore,'Repeat render uses cached chunks');
await evaluate(`document.querySelector('#search').value='51.34, 12.37';document.querySelector('#search-form').requestSubmit();`);
await until(`document.querySelectorAll('[data-candidate]').length===3`);
assert.ok(await evaluate(`document.querySelector('#results').textContent.includes('Noch nicht bezifferbar')`));
await evaluate(`document.querySelector('[data-candidate]').click()`);assert.ok(await evaluate(`document.querySelector('#detail-dialog').open`));
await evaluate(`document.querySelector('[data-close="detail-dialog"]').click();document.querySelector('#open-model').click();`);
await evaluate(`document.querySelectorAll('[data-price]').forEach(el=>el.value=[10,20,30][Number(el.dataset.scenario)]);document.querySelector('#crossings').value=2;document.querySelector('#model-source').value='AUTOMATED TEST ONLY';document.querySelector('#price-date').value='2026-10-08';document.querySelector('#model-form').requestSubmit();`);
await until(`document.querySelector('#results').textContent.includes('Modellbandbreite')`);
await evaluate(`document.querySelector('#save-site').click();document.querySelector('#search').value='52.52, 13.405';document.querySelector('#search-form').requestSubmit();`);
await until(`document.querySelectorAll('[data-candidate]').length===3`);
await evaluate(`document.querySelector('#save-site').click();document.querySelector('#compare-tab').click();`);
await until(`document.querySelectorAll('.compare-card').length===2`);
await evaluate(`document.querySelector('#plan-tab').click()`);
const result=await evaluate(`window.testTools.configure_connection_site.execute({latitude:48.137,longitude:11.575,powerMW:10})`);
assert.equal(result.candidates.length,3);assert.equal(result.powerMW,10);
await evaluate(`document.querySelector('#export').click()`);
await until(`document.querySelector('#print-report').innerHTML.includes('Standort 2')`);
assert.ok(await evaluate(`document.querySelector('#print-report svg')!==null`));
await send('Network.setBlockedURLs',{urls:['*tile.openstreetmap.org/*','*wms.nrw.de/*','*DE-HH-stations.json*']});
await evaluate(`window.testTools.configure_connection_site.execute({latitude:53.55,longitude:10,powerMW:10})`);
assert.ok(await evaluate(`document.querySelector('#results').textContent.includes('erneut wählen')`),'Download error is explicit');
assert.equal(await evaluate(`document.querySelectorAll('[data-candidate]').length`),0,'No stale results after failed load');
assert.ok(await evaluate(`document.querySelector('#save-site').disabled`));
await send('Network.setBlockedURLs',{urls:['*tile.openstreetmap.org/*','*wms.nrw.de/*']});
await evaluate(`document.querySelector('#retry-data').click()`);
await until(`document.querySelectorAll('[data-candidate]').length===3`);
await evaluate(`document.querySelector('#search').value='52.52, 13.405';document.querySelector('#search-form').requestSubmit();document.querySelector('#search').value='48.137, 11.575';document.querySelector('#search-form').requestSubmit();`);
await until(`document.querySelectorAll('[data-candidate]').length===3`);
await wait(400);
const latest=await evaluate(`window.testTools.read_connection_estimates.execute()`);assert.equal(latest.site.lat,48.137);assert.ok(latest.results.every(r=>r.distanceKm<50));
await evaluate(`document.querySelector('#fit-germany').click()`);
await until(`document.querySelector('#data-status').textContent.includes('16 Bundesländer')`);
assert.equal(await evaluate(`document.querySelector('#state-filter').value`),'');
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await wait(500);
assert.ok(await evaluate(`document.documentElement.scrollWidth<=innerWidth+1`),'No mobile overflow');
await evaluate(`document.querySelector('.map-section').scrollIntoView()`);await wait(100);
const mobileMap=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});writeFileSync('/tmp/anschluss-regions-results/mobile-map.png',Buffer.from(mobileMap.data,'base64'));
await evaluate(`document.querySelector('#power').value=0;document.querySelector('#power').dispatchEvent(new Event('change'));`);
assert.equal(await evaluate(`document.querySelectorAll('[data-candidate]').length`),0);
assert.ok(await evaluate(`document.querySelector('#save-site').disabled`));
assert.equal(errors.length,0,JSON.stringify(errors));
mkdirSync('/tmp/anschluss-regions-results',{recursive:true});
const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});writeFileSync('/tmp/anschluss-regions-results/mobile.png',Buffer.from(shot.data,'base64'));
const results={passed:true,initial,regionalRequests:requests.filter(url=>url.includes('data/states/')),longTasks:await evaluate('window.longTasks'),errors};
writeFileSync('/tmp/anschluss-regions-results/results.json',JSON.stringify(results,null,2));
console.log(JSON.stringify(results,null,2));ws.close();
